name: Faabric tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - docker

jobs:
  tests:
    runs-on: ubuntu-18.04
    env:
      HOST_TYPE: ci
      REDIS_QUEUE_HOST: redis
      REDIS_STATE_HOST: redis
    container:
      image: faabric/base:0.0.1
    services:
      redis:
        image: redis
    steps:
      - uses: actions/checkout@v2
      - name: "Install redis stuff"
        run: apt install -y redis-tools
      - name: "Ping redis"
        run: redis-cli -h redis ping
      - name: "Make Catch dir"
        run: mkdir -p /usr/local/include/catch
      - name: "Install Catch"
        run: >
          wget -q -O /usr/local/include/catch/catch.hpp
          https://raw.githubusercontent.com/catchorg/Catch2/master/single_include/catch2/catch.hpp
      - name: "Create build dir"
        run: mkdir build
      - name: "Set up build"
        run: >
          cmake
          -GNinja
          -DCMAKE_BUILD_TYPE=Release
          ..
        working-directory: build
      - name: "Build tests"
        run: cmake --build . --target faabric_tests
        working-directory: build
      - name: "Run tests"
        run: ./bin/faabric_tests
        working-directory: build
