name: Faabric tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - docker

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/tests-container

